### path variable
GET http://localhost:8080/api/v1/hello/goodall/30

### request param
GET http://localhost:8080/api/v1/hello/query-params?age=30&name=goodall&phone-number=010-1234-5678

### request param default-test
GET http://localhost:8080/api/v1/hello/default-test1

### request param fail 500
GET http://localhost:8080/api/v1/hello/query-params/without-annotation?age=30

### request param fail 400
GET http://localhost:8080/api/v1/hello/query-params/without-annotation?name=goodall

### request param (object)
GET http://localhost:8080/api/v1/hello/query-params/object?age=30&name=goodall&phoneNumber=010-1234-5678

### request param (object without annotation) 400
GET http://localhost:8080/api/v1/hello/query-params/object/without-annotation

### request param (map)
GET http://localhost:8080/api/v1/hello/query-params/map?name=goodall

### with validate FAIL (GET) [Valid(파라메터), MethodArgumentValidException] 4xx ERROR
GET http://localhost:8080/api/v1/validate/sample2?age=101&name=goodall&phoneNumber=010-1234-5678

### with validate FAIL (GET) [Valided(파라메터), MethodArgumentValidException] 4xx ERROR
GET http://localhost:8080/api/v1/validate/sample21?age=101&name=goodall&phoneNumber=010-1234-5678

### with validate FAIL (Post) [Validate(클래스), ConstraintViolationException] 5xx ERROR
POST http://localhost:8080/api/v1/validate/sample1?age=0


### with validate (Post)
POST http://localhost:8080/api/v1/validate/sample2
Content-Type: application/json

{
  "name": "goodall",
  "age": 30
}

### Fail with validate (Post)
POST http://localhost:8080/api/v1/validate/sample2
Content-Type: application/json

{
  "name": "unluckyjung",
  "age": 101
}

### Fail with validate (Post)
POST http://localhost:8080/api/v1/validate/sample2
Content-Type: application/json

{
  "name": "jys",
  "age": 29
}

### Fail with custom annotation validate (Post)
POST http://localhost:8080/api/v1/validate/sample2
Content-Type: application/json

{
  "name": "goodall",
  "age": 29
}

### PathVariable Defalt Value Test
GET http://localhost:8080/api/v1/hello/30/default-test1

### RequestParam Default Value Test (return null)
GET http://localhost:8080/api/v1/hello/query-params/default-test2

### RequestParam Default Value Test (return default value)
GET http://localhost:8080/api/v1/hello/query-params/default-test1


### Exception Basic
GET http://localhost:8080/api/v1/exception/basic


### Exception age
GET http://localhost:8080/api/v1/exception/age
Content-Type: application/json

{
  "age": -1
}

### Exception Custom Validation Annotation (ReqeustBody)
GET http://localhost:8080/api/v1/exception/nickName
Content-Type: application/json

{
  "nickName": "goodall"
}

### Exception Custom Validation Annotation (Param)
GET http://localhost:8080/api/v1/exception/nickName2?nickName=goodall