### path variable
GET http://localhost:8080/api/v1/hello/goodall/30

### request param
GET http://localhost:8080/api/v1/hello/query-params?age=30&name=goodall&phone-number=010-1234-5678

### request param fail 500
GET http://localhost:8080/api/v1/hello/query-params/without-annotation?age=30

### request param fail 400
GET http://localhost:8080/api/v1/hello/query-params/without-annotation?name=goodall

### request param (object)
GET http://localhost:8080/api/v1/hello/query-params/object?age=30&name=goodall&phoneNumber=010-1234-5678

### request param (object without annotation) 400
GET http://localhost:8080/api/v1/hello/query-params/object/without-annotation

### request param (map)
GET http://localhost:8080/api/v1/hello/query-params/map?name=goodall

### with validate FAIL (GET) [Valid, MethodArgumentValidException] 4xx ERROR
GET http://localhost:8080/api/v1/validate/sample2?age=101&name=goodall&phoneNumber=010-1234-5678

### with validate Fail (Post) [Validate, ConstraintViolationException] 5xx ERROR
POST http://localhost:8080/api/v1/validate/sample1?age=0


### with validate (Post)
POST http://localhost:8080/api/v1/validate/sample2
Content-Type: application/json

{
  "name": "goodall",
  "age": 30
}

### Fail with validate (Post)
POST http://localhost:8080/api/v1/validate/sample2
Content-Type: application/json

{
  "name": "unluckyjung",
  "age": 101
}

### Fail with validate (Post)
POST http://localhost:8080/api/v1/validate/sample2
Content-Type: application/json

{
  "name": "jys",
  "age": 29
}